name: ml_assignments_env
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - jupyter
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - pytorch=2.3.0
  - tensorboard=2.17.0
  - pyspark=3.5.0